# Generated by Django 4.0.4 on 2022-06-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('participantes', models.IntegerField()),
                ('virtual', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apeliido', models.CharField(max_length=20)),
                ('profesion', models.CharField(max_length=20)),
                ('enfoque', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apeliido', models.CharField(max_length=20)),
                ('profesion', models.CharField(max_length=20)),
                ('busqueda', models.CharField(max_length=30)),
            ],
        ),
    ]
