# Generated by Django 4.0.4 on 2022-06-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiderApp', '0002_remove_actividad_virtual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lider',
            old_name='apeliido',
            new_name='apellido',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='participantes',
        ),
        migrations.AddField(
            model_name='actividad',
            name='apellido',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='webinar',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lider',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
